# services:
#   zookeeper:
#     image: zookeeper:3.9.3  # Using the specific version of Zookeeper
#     ports:
#       - "2181:2181"
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181

#   kafka:
#     image: wurstmeister/kafka:latest
#     ports:
#       - "9093:9093"
#     expose:
#       - "9093"
#     environment:
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_LISTENER_NAME_INTERNAL: INSIDE
#       KAFKA_LISTENER_INTERNAL: INSIDE://kafka:9093
#       KAFKA_LISTENERS: INSIDE://0.0.0.0:9093  # Added KAFKA_LISTENERS
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
#       KAFKA_LISTENER_PORT: 9093
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#     depends_on:
#       - zookeeper
version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.9.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
